# config for doctor - dev

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lunecare?currentSchema=doctor
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
