# ROOT application.yml
# Shared defaults inherited by ALL services automatically.
# Spring Cloud Config serves this to every service regardless of name, override per-service
# or per-profile as per requirement.

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh, prometheus, metrics
  endpoint:
    busrefresh:
      access: unrestricted
    health:
      show-details: always
      probes:
        enabled: true
    info:
      access: unrestricted
    shutdown:
      enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  info:
    env:
      enabled: true
  # For micrometer-prometheous metrics, make sure mention the tags that should be the name wrt each microservice
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    bus:
      enabled: true
      id: ${spring.application.name}:${server.port}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5000

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    filter: true