# config for payment - docker profile
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/lunecare?currentSchema=payment
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}