# config for config-server - prod

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}  # Use GitHub PAT (Personal Access Token)
