# config for config-server - dev

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI:https://github.com/ripanbaidya/lune-care-config.git}
          # No auth needed for public repo in dev
