# config for patient - prod

spring:
  datasource:
    url: ${PATIENT_DB_URL}
    username: ${PATIENT_DB_USERNAME}
    password: ${PATIENT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 3
  jpa:
    show-sql: false
